### ISSUE TITLE
switchedTimePattern was not declared in this scope error while upload

### ISSUE THREAD

**Issue by Github-Anni** [NimmLor/esp8266-fastled-iot-webserver#83] opened 2020-11-25 21:38 UTC
i try to compile and upload in arduino but receive the following error:

Arduino: 1.8.13 (Windows 10), Board: "LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Disabled (new can abort), All SSL ciphers (most compatible), 4MB (FS:1MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"
                       ^
**_D:\esp8266-fastled-iot-webserver\esp8266-fastled-iot-webserver.ino: In lambda function:
esp8266-fastled-iot-webserver:1018:9: error: 'switchedTimePattern' was not declared in this scope
         switchedTimePattern = true;
         ^
exit status 1
'switchedTimePattern' was not declared in this scope_**

Used libraries:
Bibliothek FastLED in Version 3.3.2 im Ordner: C:\Users\xxx\Documents\Arduino\libraries\FastLED  wird verwendet
Bibliothek ESP8266WiFi in Version 1.0 im Ordner: C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.0\libraries\ESP8266WiFi  wird verwendet
Bibliothek ESP8266WebServer in Version 1.0 im Ordner: C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.0\libraries\ESP8266WebServer  wird verwendet
Bibliothek EEPROM in Version 1.0 im Ordner: C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.0\libraries\EEPROM  wird verwendet
Bibliothek Espalexa in Version 2.4.4 im Ordner: C:\Users\xxx\Documents\Arduino\libraries\Espalexa  wird verwendet
Bibliothek ESP8266mDNS in Version 1.2 im Ordner: C:\Users\xxx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.0\libraries\ESP8266mDNS  wird verwendet

any idea how to fix this?

Thank you

**Comment by NimmLor** [comment] 2020-11-25 21:59
duplicate of #81

fixed in the latest release/commit

feel free to re-open this issue if the error persists

**Closed as completed by NimmLor** 2020-11-25 21:59 UTC
